### ISSUE TITLE
Cat. Icons are not proper

### ISSUE THREAD

**Issue by rexs123** [OzairP/onyx#10]
Viewing the provided image below; you'll see that the image to the forum category is out of line / not fully sized. 

IMAGE REFERENCE: http://i.rexsdev.com/chrome_2016-10-04_20-30-15.png

I recommend using two different toned MCM Logo's for read & unread threads.

**Comment by OzairP** [comment]
Please provide more information such as links, or expand your description of the issue.

**Comment by pwign** [comment]
There is no issue for me: https://10.lithi.io/uOKuHN.png
