### ISSUE TITLE
Hovering on nav

### ISSUE THREAD

**Issue by rexs123** [OzairP/onyx#13]
Not really an issue but look at the provided image below;

IMAGE REFERENCE: http://i.rexsdev.com/chrome_2016-10-04_20-39-03.png 

I recommend adding some margin-left to the hover. Cus well it hugs the text.

**Comment by OzairP** [comment]
Please provide more information such as links, or expand your description of the issue.

**Comment by rexs123** [comment]
The "hover" background-color is off-sized, could be increased on the left and right sides to look a bit better.
